#!/usr/bin/env perl
use warnings;
use strict;


my (@javaopts, $class, @otheropts);

for (@ARGV) {
	if (not defined $class) {
		if (/^-/) {
			push @javaopts, $_;
		} else {
			$class = $_;
		}
	} else {
		push @otheropts, $_;
	}
}

print STDERR "searching class: $class\n";

my ($project, $realclass) = split /\t/, `find-class $class`, 2;

print "project: $project\n";
print "realclass: $realclass\n";

system("ecl-classpath-java $project ".join(" ", @javaopts)." org.junit.runner.JUnitCore $realclass ".join(" ", @otheropts));
